### ISSUE TITLE
Dialog会拖出边界

### ISSUE THREAD

**Issue by oojeek** [bigtrouble/vue-element-dialog-drag#2]
当向上拖动Dialog时，会将Dialog拖到body外区域，这样就拖不回来了，该问题能否解决一下？

**Comment by tonyplayboy** [comment]
按照这步修改源代码,
1.打开vue-element-dialog-draggable模块下的index.js
2.找到第23行----dlg.style.top = (e.pageY - dlg.offsetY)<0 + 'px';
修改为---  dlg.style.top = ((e.pageY - dlg.offsetY)<0 ? 0 :(e.pageY - dlg.offsetY)) + 'px';
修改后, 拖拽就限制了拖拽的上限为浏览器页面顶部
作者按这个能否改一下? @bigtrouble

**Comment by bigtrouble** [comment]
@oojeek 
@tonyplayboy 
Has been fixed in v1.1.0

```javascript
import DlgDraggable from "vue-element-dialog-draggable"
Vue.use(DlgDraggable, {
  // Constrains dragging to within the bounds of the window.  
  // Default: false.
  containment: true
});
```
